package libkafka

import "fmt"

type Error struct {
	Code    int16
	Message string
}

func (e Error) Error() string {
	s := fmt.Sprintf("error code %d (%s)", e.Code, errorDescriptions[int(e.Code)])
	if e.Message != "" {
		s += ": " + e.Message
	}
	return s
}

const (
	ERR_UNKNOWN_SERVER_ERROR                  = -1
	ERR_NONE                                  = 0
	ERR_OFFSET_OUT_OF_RANGE                   = 1
	ERR_CORRUPT_MESSAGE                       = 2 // retriable: True
	ERR_UNKNOWN_TOPIC_OR_PARTITION            = 3 // retriable: True
	ERR_INVALID_FETCH_SIZE                    = 4
	ERR_LEADER_NOT_AVAILABLE                  = 5 // retriable: True
	ERR_NOT_LEADER_FOR_PARTITION              = 6 // retriable: True
	ERR_REQUEST_TIMED_OUT                     = 7 // retriable: True
	ERR_BROKER_NOT_AVAILABLE                  = 8
	ERR_REPLICA_NOT_AVAILABLE                 = 9
	ERR_MESSAGE_TOO_LARGE                     = 10
	ERR_STALE_CONTROLLER_EPOCH                = 11
	ERR_OFFSET_METADATA_TOO_LARGE             = 12
	ERR_NETWORK_EXCEPTION                     = 13 // retriable: True
	ERR_COORDINATOR_LOAD_IN_PROGRESS          = 14 // retriable: True
	ERR_COORDINATOR_NOT_AVAILABLE             = 15 // retriable: True
	ERR_NOT_COORDINATOR                       = 16 // retriable: True
	ERR_INVALID_TOPIC_EXCEPTION               = 17
	ERR_RECORD_LIST_TOO_LARGE                 = 18
	ERR_NOT_ENOUGH_REPLICAS                   = 19 // retriable: True
	ERR_NOT_ENOUGH_REPLICAS_AFTER_APPEND      = 20 // retriable: True
	ERR_INVALID_REQUIRED_ACKS                 = 21
	ERR_ILLEGAL_GENERATION                    = 22
	ERR_INCONSISTENT_GROUP_PROTOCOL           = 23
	ERR_INVALID_GROUP_ID                      = 24
	ERR_UNKNOWN_MEMBER_ID                     = 25
	ERR_INVALID_SESSION_TIMEOUT               = 26
	ERR_REBALANCE_IN_PROGRESS                 = 27
	ERR_INVALID_COMMIT_OFFSET_SIZE            = 28
	ERR_TOPIC_AUTHORIZATION_FAILED            = 29
	ERR_GROUP_AUTHORIZATION_FAILED            = 30
	ERR_CLUSTER_AUTHORIZATION_FAILED          = 31
	ERR_INVALID_TIMESTAMP                     = 32
	ERR_UNSUPPORTED_SASL_MECHANISM            = 33
	ERR_ILLEGAL_SASL_STATE                    = 34
	ERR_UNSUPPORTED_VERSION                   = 35
	ERR_TOPIC_ALREADY_EXISTS                  = 36
	ERR_INVALID_PARTITIONS                    = 37
	ERR_INVALID_REPLICATION_FACTOR            = 38
	ERR_INVALID_REPLICA_ASSIGNMENT            = 39
	ERR_INVALID_CONFIG                        = 40
	ERR_NOT_CONTROLLER                        = 41 // retriable: True
	ERR_INVALID_REQUEST                       = 42
	ERR_UNSUPPORTED_FOR_MESSAGE_FORMAT        = 43
	ERR_POLICY_VIOLATION                      = 44
	ERR_OUT_OF_ORDER_SEQUENCE_NUMBER          = 45
	ERR_DUPLICATE_SEQUENCE_NUMBER             = 46
	ERR_INVALID_PRODUCER_EPOCH                = 47
	ERR_INVALID_TXN_STATE                     = 48
	ERR_INVALID_PRODUCER_ID_MAPPING           = 49
	ERR_INVALID_TRANSACTION_TIMEOUT           = 50
	ERR_CONCURRENT_TRANSACTIONS               = 51
	ERR_TRANSACTION_COORDINATOR_FENCED        = 52
	ERR_TRANSACTIONAL_ID_AUTHORIZATION_FAILED = 53
	ERR_SECURITY_DISABLED                     = 54
	ERR_OPERATION_NOT_ATTEMPTED               = 55
	ERR_KAFKA_STORAGE_ERROR                   = 56 // retriable: True
	ERR_LOG_DIR_NOT_FOUND                     = 57
	ERR_SASL_AUTHENTICATION_FAILED            = 58
	ERR_UNKNOWN_PRODUCER_ID                   = 59
	ERR_REASSIGNMENT_IN_PROGRESS              = 60
	ERR_DELEGATION_TOKEN_AUTH_DISABLED        = 61
	ERR_DELEGATION_TOKEN_NOT_FOUND            = 62
	ERR_DELEGATION_TOKEN_OWNER_MISMATCH       = 63
	ERR_DELEGATION_TOKEN_REQUEST_NOT_ALLOWED  = 64
	ERR_DELEGATION_TOKEN_AUTHORIZATION_FAILED = 65
	ERR_DELEGATION_TOKEN_EXPIRED              = 66
	ERR_INVALID_PRINCIPAL_TYPE                = 67
	ERR_NON_EMPTY_GROUP                       = 68
	ERR_GROUP_ID_NOT_FOUND                    = 69
	ERR_FETCH_SESSION_ID_NOT_FOUND            = 70 // retriable: True
	ERR_INVALID_FETCH_SESSION_EPOCH           = 71 // retriable: True
	ERR_LISTENER_NOT_FOUND                    = 72 // retriable: True
	ERR_TOPIC_DELETION_DISABLED               = 73
	ERR_FENCED_LEADER_EPOCH                   = 74 // retriable: True
	ERR_UNKNOWN_LEADER_EPOCH                  = 75 // retriable: True
	ERR_UNSUPPORTED_COMPRESSION_TYPE          = 76
	ERR_STALE_BROKER_EPOCH                    = 77
	ERR_OFFSET_NOT_AVAILABLE                  = 78 // retriable: True
	ERR_MEMBER_ID_REQUIRED                    = 79
	ERR_PREFERRED_LEADER_NOT_AVAILABLE        = 80 // retriable: True
	ERR_GROUP_MAX_SIZE_REACHED                = 81
)

var errorDescriptions = map[int]string{
	-1: "UNKNOWN_SERVER_ERROR",
	0:  "NONE",
	1:  "OFFSET_OUT_OF_RANGE",
	2:  "CORRUPT_MESSAGE",
	3:  "UNKNOWN_TOPIC_OR_PARTITION",
	4:  "INVALID_FETCH_SIZE",
	5:  "LEADER_NOT_AVAILABLE",
	6:  "NOT_LEADER_FOR_PARTITION",
	7:  "REQUEST_TIMED_OUT",
	8:  "BROKER_NOT_AVAILABLE",
	9:  "REPLICA_NOT_AVAILABLE",
	10: "MESSAGE_TOO_LARGE",
	11: "STALE_CONTROLLER_EPOCH",
	12: "OFFSET_METADATA_TOO_LARGE",
	13: "NETWORK_EXCEPTION",
	14: "COORDINATOR_LOAD_IN_PROGRESS",
	15: "COORDINATOR_NOT_AVAILABLE",
	16: "NOT_COORDINATOR",
	17: "INVALID_TOPIC_EXCEPTION",
	18: "RECORD_LIST_TOO_LARGE",
	19: "NOT_ENOUGH_REPLICAS",
	20: "NOT_ENOUGH_REPLICAS_AFTER_APPEND",
	21: "INVALID_REQUIRED_ACKS",
	22: "ILLEGAL_GENERATION",
	23: "INCONSISTENT_GROUP_PROTOCOL",
	24: "INVALID_GROUP_ID",
	25: "UNKNOWN_MEMBER_ID",
	26: "INVALID_SESSION_TIMEOUT",
	27: "REBALANCE_IN_PROGRESS",
	28: "INVALID_COMMIT_OFFSET_SIZE",
	29: "TOPIC_AUTHORIZATION_FAILED",
	30: "GROUP_AUTHORIZATION_FAILED",
	31: "CLUSTER_AUTHORIZATION_FAILED",
	32: "INVALID_TIMESTAMP",
	33: "UNSUPPORTED_SASL_MECHANISM",
	34: "ILLEGAL_SASL_STATE",
	35: "UNSUPPORTED_VERSION",
	36: "TOPIC_ALREADY_EXISTS",
	37: "INVALID_PARTITIONS",
	38: "INVALID_REPLICATION_FACTOR",
	39: "INVALID_REPLICA_ASSIGNMENT",
	40: "INVALID_CONFIG",
	41: "NOT_CONTROLLER",
	42: "INVALID_REQUEST",
	43: "UNSUPPORTED_FOR_MESSAGE_FORMAT",
	44: "POLICY_VIOLATION",
	45: "OUT_OF_ORDER_SEQUENCE_NUMBER",
	46: "DUPLICATE_SEQUENCE_NUMBER",
	47: "INVALID_PRODUCER_EPOCH",
	48: "INVALID_TXN_STATE",
	49: "INVALID_PRODUCER_ID_MAPPING",
	50: "INVALID_TRANSACTION_TIMEOUT",
	51: "CONCURRENT_TRANSACTIONS",
	52: "TRANSACTION_COORDINATOR_FENCED",
	53: "TRANSACTIONAL_ID_AUTHORIZATION_FAILED",
	54: "SECURITY_DISABLED",
	55: "OPERATION_NOT_ATTEMPTED",
	56: "KAFKA_STORAGE_ERROR",
	57: "LOG_DIR_NOT_FOUND",
	58: "SASL_AUTHENTICATION_FAILED",
	59: "UNKNOWN_PRODUCER_ID",
	60: "REASSIGNMENT_IN_PROGRESS",
	61: "DELEGATION_TOKEN_AUTH_DISABLED",
	62: "DELEGATION_TOKEN_NOT_FOUND",
	63: "DELEGATION_TOKEN_OWNER_MISMATCH",
	64: "DELEGATION_TOKEN_REQUEST_NOT_ALLOWED",
	65: "DELEGATION_TOKEN_AUTHORIZATION_FAILED",
	66: "DELEGATION_TOKEN_EXPIRED",
	67: "INVALID_PRINCIPAL_TYPE",
	68: "NON_EMPTY_GROUP",
	69: "GROUP_ID_NOT_FOUND",
	70: "FETCH_SESSION_ID_NOT_FOUND",
	71: "INVALID_FETCH_SESSION_EPOCH",
	72: "LISTENER_NOT_FOUND",
	73: "TOPIC_DELETION_DISABLED",
	74: "FENCED_LEADER_EPOCH",
	75: "UNKNOWN_LEADER_EPOCH",
	76: "UNSUPPORTED_COMPRESSION_TYPE",
	77: "STALE_BROKER_EPOCH",
	78: "OFFSET_NOT_AVAILABLE",
	79: "MEMBER_ID_REQUIRED",
	80: "PREFERRED_LEADER_NOT_AVAILABLE",
	81: "GROUP_MAX_SIZE_REACHED",
}
