package errors

import "fmt"

type KafkaError struct {
	Code    int16
	Message string
}

func (e *KafkaError) Error() string {
	s := fmt.Sprintf("error code %d (%s)", e.Code, Descriptions[int(e.Code)])
	if e.Message != "" {
		s += ": " + e.Message
	}
	return s
}

const (
	UNKNOWN_SERVER_ERROR                  = -1
	NONE                                  = 0
	OFFSET_OUT_OF_RANGE                   = 1
	CORRUPT_MESSAGE                       = 2 // retriable: True
	UNKNOWN_TOPIC_OR_PARTITION            = 3 // retriable: True
	INVALID_FETCH_SIZE                    = 4
	LEADER_NOT_AVAILABLE                  = 5 // retriable: True
	NOT_LEADER_FOR_PARTITION              = 6 // retriable: True
	REQUEST_TIMED_OUT                     = 7 // retriable: True
	BROKER_NOT_AVAILABLE                  = 8
	REPLICA_NOT_AVAILABLE                 = 9
	MESSAGE_TOO_LARGE                     = 10
	STALE_CONTROLLER_EPOCH                = 11
	OFFSET_METADATA_TOO_LARGE             = 12
	NETWORK_EXCEPTION                     = 13 // retriable: True
	COORDINATOR_LOAD_IN_PROGRESS          = 14 // retriable: True
	COORDINATOR_NOT_AVAILABLE             = 15 // retriable: True
	NOT_COORDINATOR                       = 16 // retriable: True
	INVALID_TOPIC_EXCEPTION               = 17
	RECORD_LIST_TOO_LARGE                 = 18
	NOT_ENOUGH_REPLICAS                   = 19 // retriable: True
	NOT_ENOUGH_REPLICAS_AFTER_APPEND      = 20 // retriable: True
	INVALID_REQUIRED_ACKS                 = 21
	ILLEGAL_GENERATION                    = 22
	INCONSISTENT_GROUP_PROTOCOL           = 23
	INVALID_GROUP_ID                      = 24
	UNKNOWN_MEMBER_ID                     = 25
	INVALID_SESSION_TIMEOUT               = 26
	REBALANCE_IN_PROGRESS                 = 27
	INVALID_COMMIT_OFFSET_SIZE            = 28
	TOPIC_AUTHORIZATION_FAILED            = 29
	GROUP_AUTHORIZATION_FAILED            = 30
	CLUSTER_AUTHORIZATION_FAILED          = 31
	INVALID_TIMESTAMP                     = 32
	UNSUPPORTED_SASL_MECHANISM            = 33
	ILLEGAL_SASL_STATE                    = 34
	UNSUPPORTED_VERSION                   = 35
	TOPIC_ALREADY_EXISTS                  = 36
	INVALID_PARTITIONS                    = 37
	INVALID_REPLICATION_FACTOR            = 38
	INVALID_REPLICA_ASSIGNMENT            = 39
	INVALID_CONFIG                        = 40
	NOT_CONTROLLER                        = 41 // retriable: True
	INVALID_REQUEST                       = 42
	UNSUPPORTED_FOR_MESSAGE_FORMAT        = 43
	POLICY_VIOLATION                      = 44
	OUT_OF_ORDER_SEQUENCE_NUMBER          = 45
	DUPLICATE_SEQUENCE_NUMBER             = 46
	INVALID_PRODUCER_EPOCH                = 47
	INVALID_TXN_STATE                     = 48
	INVALID_PRODUCER_ID_MAPPING           = 49
	INVALID_TRANSACTION_TIMEOUT           = 50
	CONCURRENT_TRANSACTIONS               = 51
	TRANSACTION_COORDINATOR_FENCED        = 52
	TRANSACTIONAL_ID_AUTHORIZATION_FAILED = 53
	SECURITY_DISABLED                     = 54
	OPERATION_NOT_ATTEMPTED               = 55
	KAFKA_STORAGE_ERROR                   = 56 // retriable: True
	LOG_DIR_NOT_FOUND                     = 57
	SASL_AUTHENTICATION_FAILED            = 58
	UNKNOWN_PRODUCER_ID                   = 59
	REASSIGNMENT_IN_PROGRESS              = 60
	DELEGATION_TOKEN_AUTH_DISABLED        = 61
	DELEGATION_TOKEN_NOT_FOUND            = 62
	DELEGATION_TOKEN_OWNER_MISMATCH       = 63
	DELEGATION_TOKEN_REQUEST_NOT_ALLOWED  = 64
	DELEGATION_TOKEN_AUTHORIZATION_FAILED = 65
	DELEGATION_TOKEN_EXPIRED              = 66
	INVALID_PRINCIPAL_TYPE                = 67
	NON_EMPTY_GROUP                       = 68
	GROUP_ID_NOT_FOUND                    = 69
	FETCH_SESSION_ID_NOT_FOUND            = 70 // retriable: True
	INVALID_FETCH_SESSION_EPOCH           = 71 // retriable: True
	LISTENER_NOT_FOUND                    = 72 // retriable: True
	TOPIC_DELETION_DISABLED               = 73
	FENCED_LEADER_EPOCH                   = 74 // retriable: True
	UNKNOWN_LEADER_EPOCH                  = 75 // retriable: True
	UNSUPPORTED_COMPRESSION_TYPE          = 76
	STALE_BROKER_EPOCH                    = 77
	OFFSET_NOT_AVAILABLE                  = 78 // retriable: True
	MEMBER_ID_REQUIRED                    = 79
	PREFERRED_LEADER_NOT_AVAILABLE        = 80 // retriable: True
	GROUP_MAX_SIZE_REACHED                = 81
)

var Descriptions = map[int]string{
	-1: "UNKNOWN_SERVER_ERROR",
	0:  "NONE",
	1:  "OFFSET_OUT_OF_RANGE",
	2:  "CORRUPT_MESSAGE",
	3:  "UNKNOWN_TOPIC_OR_PARTITION",
	4:  "INVALID_FETCH_SIZE",
	5:  "LEADER_NOT_AVAILABLE",
	6:  "NOT_LEADER_FOR_PARTITION",
	7:  "REQUEST_TIMED_OUT",
	8:  "BROKER_NOT_AVAILABLE",
	9:  "REPLICA_NOT_AVAILABLE",
	10: "MESSAGE_TOO_LARGE",
	11: "STALE_CONTROLLER_EPOCH",
	12: "OFFSET_METADATA_TOO_LARGE",
	13: "NETWORK_EXCEPTION",
	14: "COORDINATOR_LOAD_IN_PROGRESS",
	15: "COORDINATOR_NOT_AVAILABLE",
	16: "NOT_COORDINATOR",
	17: "INVALID_TOPIC_EXCEPTION",
	18: "RECORD_LIST_TOO_LARGE",
	19: "NOT_ENOUGH_REPLICAS",
	20: "NOT_ENOUGH_REPLICAS_AFTER_APPEND",
	21: "INVALID_REQUIRED_ACKS",
	22: "ILLEGAL_GENERATION",
	23: "INCONSISTENT_GROUP_PROTOCOL",
	24: "INVALID_GROUP_ID",
	25: "UNKNOWN_MEMBER_ID",
	26: "INVALID_SESSION_TIMEOUT",
	27: "REBALANCE_IN_PROGRESS",
	28: "INVALID_COMMIT_OFFSET_SIZE",
	29: "TOPIC_AUTHORIZATION_FAILED",
	30: "GROUP_AUTHORIZATION_FAILED",
	31: "CLUSTER_AUTHORIZATION_FAILED",
	32: "INVALID_TIMESTAMP",
	33: "UNSUPPORTED_SASL_MECHANISM",
	34: "ILLEGAL_SASL_STATE",
	35: "UNSUPPORTED_VERSION",
	36: "TOPIC_ALREADY_EXISTS",
	37: "INVALID_PARTITIONS",
	38: "INVALID_REPLICATION_FACTOR",
	39: "INVALID_REPLICA_ASSIGNMENT",
	40: "INVALID_CONFIG",
	41: "NOT_CONTROLLER",
	42: "INVALID_REQUEST",
	43: "UNSUPPORTED_FOR_MESSAGE_FORMAT",
	44: "POLICY_VIOLATION",
	45: "OUT_OF_ORDER_SEQUENCE_NUMBER",
	46: "DUPLICATE_SEQUENCE_NUMBER",
	47: "INVALID_PRODUCER_EPOCH",
	48: "INVALID_TXN_STATE",
	49: "INVALID_PRODUCER_ID_MAPPING",
	50: "INVALID_TRANSACTION_TIMEOUT",
	51: "CONCURRENT_TRANSACTIONS",
	52: "TRANSACTION_COORDINATOR_FENCED",
	53: "TRANSACTIONAL_ID_AUTHORIZATION_FAILED",
	54: "SECURITY_DISABLED",
	55: "OPERATION_NOT_ATTEMPTED",
	56: "KAFKA_STORAGE_ERROR",
	57: "LOG_DIR_NOT_FOUND",
	58: "SASL_AUTHENTICATION_FAILED",
	59: "UNKNOWN_PRODUCER_ID",
	60: "REASSIGNMENT_IN_PROGRESS",
	61: "DELEGATION_TOKEN_AUTH_DISABLED",
	62: "DELEGATION_TOKEN_NOT_FOUND",
	63: "DELEGATION_TOKEN_OWNER_MISMATCH",
	64: "DELEGATION_TOKEN_REQUEST_NOT_ALLOWED",
	65: "DELEGATION_TOKEN_AUTHORIZATION_FAILED",
	66: "DELEGATION_TOKEN_EXPIRED",
	67: "INVALID_PRINCIPAL_TYPE",
	68: "NON_EMPTY_GROUP",
	69: "GROUP_ID_NOT_FOUND",
	70: "FETCH_SESSION_ID_NOT_FOUND",
	71: "INVALID_FETCH_SESSION_EPOCH",
	72: "LISTENER_NOT_FOUND",
	73: "TOPIC_DELETION_DISABLED",
	74: "FENCED_LEADER_EPOCH",
	75: "UNKNOWN_LEADER_EPOCH",
	76: "UNSUPPORTED_COMPRESSION_TYPE",
	77: "STALE_BROKER_EPOCH",
	78: "OFFSET_NOT_AVAILABLE",
	79: "MEMBER_ID_REQUIRED",
	80: "PREFERRED_LEADER_NOT_AVAILABLE",
	81: "GROUP_MAX_SIZE_REACHED",
}
